app/urls.py
from django.urls import re_path
from . import views

app_name = "app" 


urlpatterns=[
    re_path('^$',views.home,name = 'homepage'),
    re_path("register", views.register_request, name="register"),
    re_path("login", views.login_request, name="login"),
    re_path("logout", views.logout_request, name= "logout"),
    re_path('index/', views.index, name='index'),
    re_path('create_profile', views.create_profile, name='create_profile'),
    re_path('profile/', views.profile, name='profile'),
    re_path('post_business/', views.post_business, name='post_business'),
    re_path('announce/', views.announcements, name='announce'),
    re_path('amenities/', views.amenities, name='amenities'),
    re_path('search/', views.search_results, name='search'),
]

hood/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django_registration.backends.one_step.views import RegistrationView
from django.contrib.auth import views as auth_views
from app import views 

app_name = "app" 


urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r"^", include("app.urls")),
    re_path('accounts/register/',
          RegistrationView.as_view(success_url='/'),
          name='django_registration_register'),
   re_path('accounts/', include('django_registration.backends.one_step.urls')),
   re_path('accounts/', include('django.contrib.auth.urls')),
   re_path('logout/',auth_views.LogoutView.as_view(template_name = 'registration/login.html'), name = 'logout'),
   re_path('password-change/', auth_views.PasswordResetView.as_view(), name='password_change'),
]

app/templates/amenity.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content%}
<div class="container-fluid">
    
    <h3 class="pt-3 text-center">Add Amenities</h3>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6"style="display:flex; justify-content:center;align-content:center;align-items:center;">
            
            <form action="" class="c" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-sm btn-warning mt-3" type="submit">Add Amenity</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row"style="display:flex; justify-content:center;align-content:center;align-items:center;">
        <h3 class="mt-3 pt-2 text-center">{{amenities|length}} Amenities Posted</h3>
        {% for amenity in amenities %}
        <div class="col-lg-4 col-md-6 mb-4 mt-5">
            <div class="card" style="background-color:white;border: 3px solid rgb(247,193,50); border-radius: 10px;">
                <div class="card-header">
                    <h4><b>{{amenity.name}}</b></h4>
                </div>
                <div class="card-title">
                    <img src="{{amenity.image.url}}" width="100%" height="280vh" class="img-responsive mb-0"
                        alt="amenity image">
                </div>
                <div class="card-footer">
                    <p>
                        Location: <b>{{amenity.location}}</b> <br>
                        Contact: <b>{{amenity.contact}}</b>
                    </p>
                </div>
            </div>
        </div>
        {% empty %}

        <div class=" col-md-12 d-flex justify-content-center alert alert-warning alert-dismissible fade show"
            role="alert">
            <strong>There are no Amenities in your Neighbourhood</strong>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/announce.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content%}
<style>
    .textarea {
        width: 8.5cm !important;
    }
</style>
<div class="container-fluid">
    <h3 class="mt-3 text-center"> Post Announcements</h3>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6" style="display:flex; justify-content:center;align-content:center;align-items:center;">

            <form action="" class="c" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-sm btn-warning mb-2" type="submit">Post Announcement</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row" style="display: flex; flex-direction: row;">
        <h3 class="mt-3 text-center"><b>{{announcements|length}} Announcements</b></h3>
        {% for announcement in announcements %}
        <div class="col-lg-4 col-md-6 mb-4 mt-5">

            <div class="card" style="background-color:white;border: 3px solid rgb(247,193,50); border-radius: 10px;height:32rem;">
                <div class="card-header">
                    <h3><b>{{announcement.title}}</b></h3>
                </div>
                <div class="card-body">
                    {{announcement.details}}
                </div>
                <div class="card-footer">
                    <p class="text-muted">
                        Posted: {{announcement.created_on|timesince}} ago <br>
                        By: {{announcement.author|capfirst}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class=" col-md-12 d-flex justify-content-center alert alert-warning alert-dismissible fade show"
            role="alert">
            <strong>There are no Announcements in your Neighbourhood</strong>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

app/templates/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Hood Connect</title>
    {% endif %}
    <link rel="icon" href="/static/images/fvcon.png" type="image/png">

    {% block styles %}
    {% bootstrap_css %}
    <link rel="shortcut icon" type="image/png" href="/static/images/favicon.png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}

</head>

<body>
    {% include "navbar.html" %}
    {% block content %}
    {%endblock%}

    {% block scripts %}
    {% bootstrap_javascript %}
    {% endblock %}

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
</body>

</html>

app/templates/business.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .textarea {
        width: 8.5cm !important;
    }
</style>

<div class="container-fluid">
    <h4 class="mt-5 text-center"><b> Post Business </b></h4> 
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6" style="display:flex; justify-content:center;align-content:center;align-items:center;">
            <form action="" class="c" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-warning mt-3" type="submit">Add business</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>

    <div class="row" style="display: flex; flex-direction: row;">
        <h3 class="mt-3 text-center"><b>{{businesses|length}} Businesses Posted</b></h3>
        
        {% for business in businesses %}
        <div class="col-lg-4 col-md-6 mb-4 mt-5">

            <div class="card"
                style="background-color:white;border: 3px solid rgb(247,193,50); border-radius: 10px;height:45rem;">
                <div class="card-header">
                    <h3><b>{{business.name}}</b></h3>
                </div>
                <div class="card-title">
                    <img src="{{business.image.url}}" width="100%" height="280vh" class="img-responsive mb-0"
                        alt="business image">
                </div>
                <div class="card-footer mt-5" style="font-size: 18px;">
                    <p class="text-muted">Address: <span class="text-dark">{{business.address}}</span></p>
                    <p class="text-muted">Owner: <span class="text-dark">{{business.owner|capfirst}}</span></p>
                    <p class="text-muted">Details: <span class="text-dark">{{business.details}}</span></p>
                    <p class="text-muted">Posted: <span class="text-dark">{{business.create_date|timesince}} ago. </span></p>
                    <p class="text-muted">Neighbourhood: <span class="text-dark">{{business.hood|capfirst}}</span></p>
                </div>
            </div>
        </div>
        {% empty %}

        <div class=" col-md-12 d-flex justify-content-center alert alert-warning alert-dismissible fade show"
            role="alert">
            <strong>There are no Businesses in your Neighbourhood</strong>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/home.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Hood Connect</title>
    {% endif %}

    {% block styles %}
    {% bootstrap_css %}
    <link rel="shortcut icon" type="image/png" href="/static/images/favicon.png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}

</head>

<body>

    {% block content %}
    <h1>test</h1>
    {%endblock%}

    {% block scripts %}
    {% bootstrap_javascript %}
    {% endblock %}

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
</body>

</html>

app/templates/index.html
{%extends 'home.html'%}
{% load static %}
{% load bootstrap5 %}
{% block content %}
<div class="container-fluid homepage">

  <div class="welcome">
    <div class="card mb-3" style="max-width: 28rem;height: 24rem;">
      <div class="card-body text-white">
        <h3 class="card-title text-dark pt-4" style="font-size: 1.85rem;">Welcome to Hood-Connect</h3>
        <p class="card-text pt-3">Keep Tabs on what is happenning in your neighbourhood, <br> build a community around
          you<br>and live <em>Freely ...</em></p>
        <a href="/login"><button type="button" class="btn btn-warning btn-lg">Join us Today!</button></a>
      </div>
    </div>

  </div>


</div>
{% endblock %}

app/templates/main.html
{%extends 'base.html'%}
{% block content %}
{{block.super}}
<style>
    .card {
        height: 75vh;
    }

    .card-footer {
        height: 45vh;
    }

</style>
<div class="container-fluid mt-2">
    <h1 class="text-center pt-3"> <b>All Posted Businesses</b></h1>

    <div class="row mt-2">
        {% if business %}
        {% for biz in business %}
        <div class="col-md-4">
            <div class="card card-default" style="background-color:white;border: 3px solid rgb(247,193,50); border-radius: 10px;">
                <div class="card-heading inline">
                    <div class="row">
                        <div class="col-md-4 mt-2 mb-2 text-center">
                            <a href="{%url 'app:profile'%}" style="color:black;">
                                <img src="{{biz.owner.profile.image.url}}" class="img-responsive rounded-circle"
                                    style="width:50px; height:50px;" alt="profile image">
                            </a>
                        </div>
                        <div class="col-md-8 mt-2 mb-2">
                            <h4><b>{{biz.name}}</b></h4>
                        </div>
                    </div>
                </div>
                <div class="card-title">
                    <div class="view" style="height: 245px; padding:2%;">
                        <img src="{{biz.image.url}}" width="100%" height="280px" class="img-responsive"
                            alt="business image">
                    </div>
                </div>
                <div class="card-footer mt-5" style="font-size: 18px;">
                    <p class="text-muted">Address: <span class="text-dark">{{biz.address}}</span></p>
                    <p class="text-muted">Owner: <span class="text-dark">{{biz.owner|capfirst}}</span></p>
                    <p class="text-muted">Details: <span class="text-dark">{{biz.details}}</span></p>
                    <p class="text-muted">Posted: <span class="text-dark">{{biz.create_date|timesince}} ago. </span></p>
                    <p class="text-muted">Neighbourhood: <span class="text-dark">{{biz.hood|capfirst}}</span></p>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
        {% else %}
        <div class="container">

            <div class=" col-md-8 d-flex justify-content-center alert alert-warning alert-dismissible fade show"
                role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <strong>
                    <p>No enterprise has been posted for view yet</p>
                </strong>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-warning">
  <a class="navbar-brand" href="/index">Hood-Connect</a>
  <div class="container">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav d-flex justify-content-center mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-center" aria-current="page" href="{% url 'app:announce' %}">Announcements</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-center" href="{% url 'app:amenities' %}">Amenities</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-center" href="{% url 'app:post_business' %}">Businesses</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-center" href="{% url 'app:create_profile' %}">Update <br> Profile</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link active text-center" href="{% url 'app:profile' %}">Profile</a>
        </li>
        <li class="nav-item active text-center">
          <a class="nav-link active text-center" href="{% url 'app:/logout">Logout</a>
        </li>
      </ul>
    </div>
    <form class="d-flex justify-content-end" role="search" action="{% url 'app:search' %}">
      <input class="form-control me-2" type="search" placeholder="Search for a Business" name="businesses">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/templates/profile.html
{%extends 'base.html'%}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4">
            <h3>Neighbourhood: <b>{{user.profile.hood}}</b></h3>
            <div class="card"style="background-color: white;">
                <div class="card-title">
                    <img src="{{user.profile.hood.image.url}}" width="100%" height="400px" class="img-responsive"
                        alt="hood image">
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-4 mb-3 mt-3">
            <div class="card" style="background-color: white;">
                <div class="card-title">
                    <img src="{{user.profile.image.url}}" width="100%" height="300px" class="img-responsive"
                        alt="profile">
                </div>
                <div class="card-footer text-center" style="background-color: white;">
                    <h2 class="text-dark">{{user.username|capfirst}}</h2>
                    <p>Hood: <b>{{user.profile.hood}}</b></p>
                    <p>Bio: <b>{{user.profile.bio}}</b></p>
                    <p>Contacts: <b>{{user.profile.contacts}}</b></p>
                    <p>Joined: <b>{{user.profile.date|timesince}} ago</b></p>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>

    </div>
</div>
{% endblock %}

app/templates/profilecreate.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<style>
    form.form-group{
        width: 100%;
        margin-left: 0.6%;
        border: 3px solid rgb(247,193,50);
        padding: 10px;
        border-radius: 10px;
        margin: 50px auto;
    }
    .col-md-10{
        text-align: center;
        font-weight: bold;
    }
    h1{
        font-size: 40px;
    }
    a{
        color: white;
    }
</style>

<div class="container-fluid mb-0 d-flex justify-content-center">
    <div class="row">
        <div class="col-md-10 d-flex justify-content-center mt-5">

            <form action="{% url 'app:create_profile' %}" class="form-group mt-3" method="post"
                enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {{u_form|crispy}}
                    {{p_form|crispy}}
                    <button type="submit" class="btn btn-sm btn-warning btn-block mt-5">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/search.html
{%extends 'base.html'%}
{% block content %}
<div class="container">
    {% if businesses %}
    <h5 class="mt-5 pb-3">Found <b>{{ businesses|length }}</b> businesses of searched term <b>{{ message }}</b></h5>
    {% else %}
    <h4 class="mt-5">Found <b> 0</b> businesses of searched term <b>{{ message }}</b></h4>
    {% endif %}
    <div class="row">
        {% if businesses %}
        {% for biz in businesses %}
        <div class="col-md-4">
            <div class="card card-default"  style="background-color:white;border: 3px solid rgb(247,193,50); border-radius: 10px;">
                <div class="card-header">
                    <h5><b>{{biz.name}}</b></h5>
                </div>
                <div class="card-title">
                    <img src="{{biz.image.url}}" width="100%" class="img-responsive" alt="searched image">
                </div>
                <div class="card-footer">
                    <p class="text-muted">Address: <span class="text-dark">{{biz.address}}</span></p>
                    <p class="text-muted">Owner: <span class="text-dark">{{biz.owner}}</span></p>
                    <p class="text-muted">Joined: <span class="text-dark">{{biz.create_date|timesince}}</span></p>
                    <p class="text-muted">Neighbourhood: <span class="text-dark">{{biz.hood}}</span></p>
                    <p class="text-muted">Details: <span class="text-dark">{{biz.details}}</span></p>
                </div>
            </div>
        </div>
        {% empty %}
        <h4>There are no posts for this enterprises.</h4>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}